# Generated by Django 2.0.13 on 2019-02-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20190221_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='Image',
            new_name='image',
        ),
    ]
